### ISSUE TITLE
Throw an error if a task not a function

### ISSUE THREAD

**Issue by zkochan** [sindresorhus/p-series#1]
I've seen on several occasions that devs were accidentally passing promises to `p-series` instead of functions that return promises. Sometimes I did this error myself and then I was wondering why the application doesn't work as it should.

Do you think it would be OK to add validation of the task. If the task is not a function, and error should be thrown.

**Comment by gluons** [comment]
It should be great if `p-series` can pass direct value like [`p-reduce`](https://github.com/sindresorhus/p-reduce).

**Comment by sindresorhus** [comment]
Yeah, good idea.
